name: Auto Sync from Upstream

on:
  workflow_dispatch:
  schedule: 
  - cron: "0 0 * * *"
  
jobs:
  Check-For-Changes:
    name: Check for changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Synchronize from Upstream
        uses: dabreadman/sync-upstream-repo@v1.0.0.b
        with:
          # URL of gitHub public upstream repo
          upstream_repo: "https://github.com/tidev/vscode-titanium"
          upstream_branch: master
          downstream_branch: master
          # GitHub Bot token
          token: ${{ secrets.GITHUB_TOKEN }}
